### ISSUE TITLE
DerbyJS Examples link at /docs is broken.

### ISSUE THREAD

**Issue by ovvn** [derbyjs/derby-site#11] opened 2014-09-28 22:54 UTC
It throws 500 with: 
"Something went wrong on our end. Try giving us a minute to fix it and then reload your browser."
Maybe it makes sense not to show the link if the examples aren't available.

**Comment by daslicht** [comment] 2015-10-25 14:39
This one is broken as well:
Add authentication to a simple Todo app.

**Comment by nateps** [comment] 2018-07-11 21:58
Thanks! Closing this, as I don't think the issue is relevant anymore. Please open a pull request or issue on derby-site for other things you might find!

**Closed by nateps** 2018-07-11 21:58 UTC
