### ISSUE TITLE
Websocket error on the main page

### ISSUE THREAD

**Issue by Margaritarita** [derbyjs/derby-site#30] opened 2016-05-15 16:52 UTC
`WebSocket connection to 'ws://render.derbyjs.com/channel' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1`
![_ _051516_125513_pm](https://cloud.githubusercontent.com/assets/16416704/15275530/448ba21c-1a9c-11e6-85e3-876ed9188828.jpg)

**Comment by nateps** [comment] 2018-07-11 22:02
The site recently received substantial updates. I'm closing this issue, since I wasn't able to reproduce it following the updates.

If this is still an issue, please re-open!

Thanks for the report! Appreciate it.

**Closed by nateps** 2018-07-11 22:02 UTC
